apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examen
  template:
    metadata:
      labels:
        app: examen
    spec:
      containers:
        - name: examen
          image: rouhou/examen-devops:dev
          ports:
            - containerPort: 80